[profile.default]
src = "src"
out = "out"
optimizer = true
solc-version = "0.8.17"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
